Bump Dockerfile.rpi to 1.64.0-buster
because:

error: package `clap_lex v0.3.1` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.63.0